#!/usr/bin/env ruby
#
# Pull TrafficServer metrics through /_stats
# ===
#
# Copyright 2012 Chris Read <chris.read@gmail.com>
#
# Based on the riak metrics collector by Pete Shima <me@peteshima.com>
#
# Released under the same terms as Sensu (the MIT license); see LICENSE
# for details.

require 'rubygems' if RUBY_VERSION < '1.9.0'
require 'sensu-plugin/metric/cli'
require 'net/http'
require 'socket'
require 'json'

class TrafficServerMetrics < Sensu::Plugin::Metric::CLI::Graphite

  option :hostname,
    :short => "-h HOSTNAME",
    :long => "--host HOSTNAME",
    :description => "TrafficServer hostname",
    :default => "localhost"

  option :port,
    :short => "-P PORT",
    :long => "--port PORT",
    :description => "TrafficServer port",
    :default => "80"

  option :path,
    :short => "-q STATUSPATH",
    :long => "--statspath STATUSPATH",
    :description => "Path to stats url",
    :default => "/_stats"

  option :scheme,
    :description => "Metric naming scheme, text to prepend to metric",
    :short => "-s SCHEME",
    :long => "--scheme SCHEME",
    :default => "#{Socket.gethostname}.trafficserver"

  def run
    res = Net::HTTP.start(config[:hostname], config[:port]) do |http|
      req = Net::HTTP::Get.new("#{config[:path]}")
      http.request(req)
    end

    body = res.body

    stats = JSON.parse(res.body)["global"]
    
    exclude = [
      "proxy.process.http.background_fill_current_count",
      "proxy.process.http.current_parent_proxy_transactions",
      "proxy.process.http.current_icp_transactions",
      "proxy.process.http.current_parent_proxy_raw_transactions",
      "proxy.process.http.current_icp_raw_transactions",
      "proxy.process.http.current_server_raw_transactions",
      "proxy.process.http.current_parent_proxy_connections",
      "proxy.process.http.current_cache_connections",
      "proxy.process.net.connections_currently_open",
      "proxy.process.net.accepts_currently_open",
      "proxy.process.socks.connections_currently_open",
      "proxy.process.cache.pread_count",
      "proxy.process.cache.lookup.success",
      "proxy.process.cache.lookup.failure",
      "proxy.process.cache.read.success",
      "proxy.process.cache.read.failure",
      "proxy.process.cache.write.success",
      "proxy.process.cache.write.failure",
      "proxy.process.cache.write.backlog.failure",
      "proxy.process.cache.update.success",
      "proxy.process.cache.update.failure",
      "proxy.process.cache.remove.success",
      "proxy.process.cache.remove.failure",
      "proxy.process.cache.evacuate.success",
      "proxy.process.cache.evacuate.failure",
      "proxy.process.cache.scan.success",
      "proxy.process.cache.scan.failure",
      "proxy.process.cache.direntries.total",
      "proxy.process.cache.direntries.used",
      "proxy.process.cache.directory_collision",
      "proxy.process.cache.frags_per_doc.1",
      "proxy.process.cache.frags_per_doc.2",
      "proxy.process.cache.frags_per_doc.3+",
      "proxy.process.cache.read_busy.success",
      "proxy.process.cache.read_busy.failure",
      "proxy.process.cache.write_bytes_stat",
      "proxy.process.cache.vector_marshals",
      "proxy.process.cache.hdr_marshals",
      "proxy.process.cache.hdr_marshal_bytes",
      "proxy.process.cache.gc_bytes_evacuated",
      "proxy.process.cache.gc_frags_evacuated",
      "proxy.process.hostdb.total_hits",
      "proxy.process.dns.success_avg_time",
      "proxy.process.dns.in_flight",
      "proxy.process.cluster.connections_open",
      "proxy.process.cluster.connections_opened",
      "proxy.process.cluster.connections_closed",
      "proxy.process.cluster.slow_ctrl_msgs_sent",
      "proxy.process.cluster.connections_locked",
      "proxy.process.cluster.reads",
      "proxy.process.cluster.read_bytes",
      "proxy.process.cluster.writes",
      "proxy.process.cluster.write_bytes",
      "proxy.process.cluster.control_messages_sent",
      "proxy.process.cluster.control_messages_received",
      "proxy.process.cluster.op_delayed_for_lock",
      "proxy.process.cluster.connections_bumped",
      "proxy.process.cluster.net_backup",
      "proxy.process.cluster.nodes",
      "proxy.process.cluster.machines_allocated",
      "proxy.process.cluster.machines_freed",
      "proxy.process.cluster.configuration_changes",
      "proxy.process.cluster.delayed_reads",
      "proxy.process.cluster.byte_bank_used",
      "proxy.process.cluster.alloc_data_news",
      "proxy.process.cluster.write_bb_mallocs",
      "proxy.process.cluster.partial_reads",
      "proxy.process.cluster.partial_writes",
      "proxy.process.cluster.cache_outstanding",
      "proxy.process.cluster.remote_op_timeouts",
      "proxy.process.cluster.remote_op_reply_timeouts",
      "proxy.process.cluster.chan_inuse",
      "proxy.process.cluster.open_delays",
      "proxy.process.cluster.connections_avg_time",
      "proxy.process.cluster.control_messages_avg_send_time",
      "proxy.process.cluster.control_messages_avg_receive_time",
      "proxy.process.cluster.open_delay_time",
      "proxy.process.cluster.cache_callback_time",
      "proxy.process.cluster.rmt_cache_callback_time",
      "proxy.process.cluster.lkrmt_cache_callback_time",
      "proxy.process.cluster.local_connection_time",
      "proxy.process.cluster.remote_connection_time",
      "proxy.process.cluster.rdmsg_assemble_time",
      "proxy.process.cluster.cluster_ping_time",
      "proxy.process.cluster.cache_callbacks",
      "proxy.process.cluster.rmt_cache_callbacks",
      "proxy.process.cluster.lkrmt_cache_callbacks",
      "proxy.process.cluster.local_connections_closed",
      "proxy.process.cluster.remote_connections_closed",
      "proxy.process.cluster.setdata_no_clustervc",
      "proxy.process.cluster.setdata_no_tunnel",
      "proxy.process.cluster.setdata_no_cachevc",
      "proxy.process.cluster.setdata_no_cluster",
      "proxy.process.cluster.vc_write_stall",
      "proxy.process.cluster.no_remote_space",
      "proxy.process.cluster.level1_bank",
      "proxy.process.cluster.multilevel_bank",
      "proxy.process.cluster.vc_cache_insert_lock_misses",
      "proxy.process.cluster.vc_cache_inserts",
      "proxy.process.cluster.vc_cache_lookup_lock_misses",
      "proxy.process.cluster.vc_cache_lookup_hits",
      "proxy.process.cluster.vc_cache_lookup_misses",
      "proxy.process.cluster.vc_cache_scans",
      "proxy.process.cluster.vc_cache_scan_lock_misses",
      "proxy.process.cluster.vc_cache_purges",
      "proxy.process.cluster.write_lock_misses",
      "proxy.process.log.log_files_open",
      "proxy.process.log.log_files_space_used",
      "proxy.process.update.successes",
      "proxy.process.update.no_actions",
      "proxy.process.update.fails",
      "proxy.process.update.unknown_status",
      "proxy.process.update.state_machines",
      "proxy.process.cache.volume_0.bytes_used",
      "proxy.process.cache.volume_0.bytes_total",
      "proxy.process.cache.volume_0.ram_cache.total_bytes",
      "proxy.process.cache.volume_0.ram_cache.bytes_used",
      "proxy.process.cache.volume_0.ram_cache.hits",
      "proxy.process.cache.volume_0.ram_cache.misses",
      "proxy.process.cache.volume_0.pread_count",
      "proxy.process.cache.volume_0.lookup.success",
      "proxy.process.cache.volume_0.lookup.failure",
      "proxy.process.cache.volume_0.read.success",
      "proxy.process.cache.volume_0.read.failure",
      "proxy.process.cache.volume_0.write.success",
      "proxy.process.cache.volume_0.write.failure",
      "proxy.process.cache.volume_0.write.backlog.failure",
      "proxy.process.cache.volume_0.update.success",
      "proxy.process.cache.volume_0.update.failure",
      "proxy.process.cache.volume_0.remove.success",
      "proxy.process.cache.volume_0.remove.failure",
      "proxy.process.cache.volume_0.evacuate.success",
      "proxy.process.cache.volume_0.evacuate.failure",
      "proxy.process.cache.volume_0.scan.success",
      "proxy.process.cache.volume_0.scan.failure",
      "proxy.process.cache.volume_0.direntries.total",
      "proxy.process.cache.volume_0.direntries.used",
      "proxy.process.cache.volume_0.directory_collision",
      "proxy.process.cache.volume_0.frags_per_doc.1",
      "proxy.process.cache.volume_0.frags_per_doc.2",
      "proxy.process.cache.volume_0.frags_per_doc.3+",
      "proxy.process.cache.volume_0.read_busy.success",
      "proxy.process.cache.volume_0.read_busy.failure",
      "proxy.process.cache.volume_0.write_bytes_stat",
      "proxy.process.cache.volume_0.vector_marshals",
      "proxy.process.cache.volume_0.hdr_marshals",
      "proxy.process.cache.volume_0.hdr_marshal_bytes",
      "proxy.process.cache.volume_0.gc_bytes_evacuated",
      "proxy.process.cache.volume_0.gc_frags_evacuated",
      "proxy.process.version.server.short",
      "proxy.process.version.server.long",
      "proxy.process.version.server.build_number",
      "proxy.process.version.server.build_time",
      "proxy.process.version.server.build_date",
      "proxy.process.version.server.build_machine",
      "proxy.process.version.server.build_person",
      "proxy.process.http.completed_requests",
      "proxy.process.http.total_client_connections",
      "proxy.process.http.total_client_connections_ipv4",
      "proxy.process.http.total_client_connections_ipv6",
      "proxy.process.http.total_server_connections",
      "proxy.process.http.total_parent_proxy_connections",
      "proxy.process.http.avg_transactions_per_client_connection",
      "proxy.process.http.avg_transactions_per_server_connection",
      "proxy.process.http.avg_transactions_per_parent_connection",
      "proxy.process.http.client_connection_time",
      "proxy.process.http.parent_proxy_connection_time",
      "proxy.process.http.server_connection_time",
      "proxy.process.http.cache_connection_time",
      "proxy.process.http.transaction_counts.errors.pre_accept_hangups",
      "proxy.process.http.transaction_totaltime.errors.pre_accept_hangups",
      "proxy.process.http.transaction_counts.errors.empty_hangups",
      "proxy.process.http.transaction_totaltime.errors.empty_hangups",
      "proxy.process.http.transaction_counts.errors.early_hangups",
      "proxy.process.http.transaction_totaltime.errors.early_hangups",
      "proxy.process.http.invalid_client_requests",
      "proxy.process.http.missing_host_hdr",
      "proxy.process.http.get_requests",
      "proxy.process.http.head_requests",
      "proxy.process.http.trace_requests",
      "proxy.process.http.options_requests",
      "proxy.process.http.post_requests",
      "proxy.process.http.put_requests",
      "proxy.process.http.push_requests",
      "proxy.process.http.delete_requests",
      "proxy.process.http.purge_requests",
      "proxy.process.http.connect_requests",
      "proxy.process.http.extension_method_requests",
      "proxy.process.http.client_no_cache_requests",
      "proxy.process.http.broken_server_connections",
      "proxy.process.http.cache_lookups",
      "proxy.process.http.cache_writes",
      "proxy.process.http.cache_updates",
      "proxy.process.http.cache_deletes",
      "proxy.process.http.tunnels",
      "proxy.process.http.throttled_proxy_only",
      "proxy.process.http.request_taxonomy.i0_n0_m0",
      "proxy.process.http.request_taxonomy.i1_n0_m0",
      "proxy.process.http.request_taxonomy.i0_n1_m0",
      "proxy.process.http.request_taxonomy.i1_n1_m0",
      "proxy.process.http.request_taxonomy.i0_n0_m1",
      "proxy.process.http.request_taxonomy.i1_n0_m1",
      "proxy.process.http.request_taxonomy.i0_n1_m1",
      "proxy.process.http.request_taxonomy.i1_n1_m1",
      "proxy.process.http.icp_suggested_lookups",
      "proxy.process.http.client_transaction_time",
      "proxy.process.http.client_write_time",
      "proxy.process.http.server_read_time",
      "proxy.process.http.icp_transaction_time",
      "proxy.process.http.icp_raw_transaction_time",
      "proxy.process.http.parent_proxy_transaction_time",
      "proxy.process.http.parent_proxy_raw_transaction_time",
      "proxy.process.http.server_transaction_time",
      "proxy.process.http.server_raw_transaction_time",
      "proxy.process.http.user_agent_request_header_total_size",
      "proxy.process.http.user_agent_response_header_total_size",
      "proxy.process.http.user_agent_request_document_total_size",
      "proxy.process.http.user_agent_response_document_total_size",
      "proxy.process.http.origin_server_request_header_total_size",
      "proxy.process.http.origin_server_response_header_total_size",
      "proxy.process.http.origin_server_request_document_total_size",
      "proxy.process.http.origin_server_response_document_total_size",
      "proxy.process.http.parent_proxy_request_total_bytes",
      "proxy.process.http.parent_proxy_response_total_bytes",
      "proxy.process.http.pushed_response_header_total_size",
      "proxy.process.http.pushed_document_total_size",
      "proxy.process.http.response_document_size_100",
      "proxy.process.http.response_document_size_1K",
      "proxy.process.http.response_document_size_3K",
      "proxy.process.http.response_document_size_5K",
      "proxy.process.http.response_document_size_10K",
      "proxy.process.http.response_document_size_1M",
      "proxy.process.http.response_document_size_inf",
      "proxy.process.http.request_document_size_100",
      "proxy.process.http.request_document_size_1K",
      "proxy.process.http.request_document_size_3K",
      "proxy.process.http.request_document_size_5K",
      "proxy.process.http.request_document_size_10K",
      "proxy.process.http.request_document_size_1M",
      "proxy.process.http.request_document_size_inf",
      "proxy.process.http.user_agent_speed_bytes_per_sec_100",
      "proxy.process.http.user_agent_speed_bytes_per_sec_1K",
      "proxy.process.http.user_agent_speed_bytes_per_sec_10K",
      "proxy.process.http.user_agent_speed_bytes_per_sec_100K",
      "proxy.process.http.user_agent_speed_bytes_per_sec_1M",
      "proxy.process.http.user_agent_speed_bytes_per_sec_10M",
      "proxy.process.http.user_agent_speed_bytes_per_sec_100M",
      "proxy.process.http.origin_server_speed_bytes_per_sec_100",
      "proxy.process.http.origin_server_speed_bytes_per_sec_1K",
      "proxy.process.http.origin_server_speed_bytes_per_sec_10K",
      "proxy.process.http.origin_server_speed_bytes_per_sec_100K",
      "proxy.process.http.origin_server_speed_bytes_per_sec_1M",
      "proxy.process.http.origin_server_speed_bytes_per_sec_10M",
      "proxy.process.http.origin_server_speed_bytes_per_sec_100M",
      "proxy.process.http.total_transactions_time",
      "proxy.process.http.total_transactions_think_time",
      "proxy.process.http.cache_hit_ims",
      "proxy.process.http.cache_hit_stale_served",
      "proxy.process.http.cache_miss_client_no_cache",
      "proxy.process.http.cache_miss_client_not_cacheable",
      "proxy.process.http.cache_miss_ims",
      "proxy.process.http.cache_read_error",
      "proxy.process.http.tcp_hit_count_stat",
      "proxy.process.http.tcp_hit_user_agent_bytes_stat",
      "proxy.process.http.tcp_hit_origin_server_bytes_stat",
      "proxy.process.http.tcp_miss_count_stat",
      "proxy.process.http.tcp_miss_user_agent_bytes_stat",
      "proxy.process.http.tcp_miss_origin_server_bytes_stat",
      "proxy.process.http.tcp_expired_miss_count_stat",
      "proxy.process.http.tcp_expired_miss_user_agent_bytes_stat",
      "proxy.process.http.tcp_expired_miss_origin_server_bytes_stat",
      "proxy.process.http.tcp_refresh_hit_count_stat",
      "proxy.process.http.tcp_refresh_hit_user_agent_bytes_stat",
      "proxy.process.http.tcp_refresh_hit_origin_server_bytes_stat",
      "proxy.process.http.tcp_refresh_miss_count_stat",
      "proxy.process.http.tcp_refresh_miss_user_agent_bytes_stat",
      "proxy.process.http.tcp_refresh_miss_origin_server_bytes_stat",
      "proxy.process.http.tcp_client_refresh_count_stat",
      "proxy.process.http.tcp_client_refresh_user_agent_bytes_stat",
      "proxy.process.http.tcp_client_refresh_origin_server_bytes_stat",
      "proxy.process.http.tcp_ims_hit_count_stat",
      "proxy.process.http.tcp_ims_hit_user_agent_bytes_stat",
      "proxy.process.http.tcp_ims_hit_origin_server_bytes_stat",
      "proxy.process.http.tcp_ims_miss_count_stat",
      "proxy.process.http.tcp_ims_miss_user_agent_bytes_stat",
      "proxy.process.http.tcp_ims_miss_origin_server_bytes_stat",
      "proxy.process.http.err_client_abort_count_stat",
      "proxy.process.http.err_client_abort_user_agent_bytes_stat",
      "proxy.process.http.err_client_abort_origin_server_bytes_stat",
      "proxy.process.http.err_connect_fail_count_stat",
      "proxy.process.http.err_connect_fail_user_agent_bytes_stat",
      "proxy.process.http.err_connect_fail_origin_server_bytes_stat",
      "proxy.process.http.misc_count_stat",
      "proxy.process.http.misc_user_agent_bytes_stat",
      "proxy.process.http.background_fill_bytes_aborted_stat",
      "proxy.process.http.background_fill_bytes_completed_stat",
      "proxy.process.http.cache_write_errors",
      "proxy.process.http.cache_read_errors",
      "proxy.process.http.transaction_counts.hit_fresh",
      "proxy.process.http.transaction_totaltime.hit_fresh",
      "proxy.process.http.transaction_counts.hit_fresh.process",
      "proxy.process.http.transaction_totaltime.hit_fresh.process",
      "proxy.process.http.transaction_counts.hit_revalidated",
      "proxy.process.http.transaction_totaltime.hit_revalidated",
      "proxy.process.http.transaction_counts.miss_cold",
      "proxy.process.http.transaction_totaltime.miss_cold",
      "proxy.process.http.transaction_counts.miss_not_cacheable",
      "proxy.process.http.transaction_totaltime.miss_not_cacheable",
      "proxy.process.http.transaction_counts.miss_changed",
      "proxy.process.http.transaction_totaltime.miss_changed",
      "proxy.process.http.transaction_counts.miss_client_no_cache",
      "proxy.process.http.transaction_totaltime.miss_client_no_cache",
      "proxy.process.http.transaction_counts.errors.aborts",
      "proxy.process.http.transaction_totaltime.errors.aborts",
      "proxy.process.http.transaction_counts.errors.possible_aborts",
      "proxy.process.http.transaction_totaltime.errors.possible_aborts",
      "proxy.process.http.transaction_counts.errors.connect_failed",
      "proxy.process.http.transaction_totaltime.errors.connect_failed",
      "proxy.process.http.transaction_counts.errors.other",
      "proxy.process.http.transaction_totaltime.errors.other",
      "proxy.process.http.transaction_counts.other.unclassified",
      "proxy.process.http.transaction_totaltime.other.unclassified",
      "proxy.process.http.total_x_redirect_count",
      "proxy.process.net.net_handler_run",
      "proxy.process.net.read_bytes",
      "proxy.process.net.write_bytes",
      "proxy.process.net.calls_to_readfromnet",
      "proxy.process.net.calls_to_readfromnet_afterpoll",
      "proxy.process.net.calls_to_read",
      "proxy.process.net.calls_to_read_nodata",
      "proxy.process.net.calls_to_writetonet",
      "proxy.process.net.calls_to_writetonet_afterpoll",
      "proxy.process.net.calls_to_write",
      "proxy.process.net.calls_to_write_nodata",
      "proxy.process.socks.connections_successful",
      "proxy.process.socks.connections_unsuccessful",
      "proxy.process.cache.read_per_sec",
      "proxy.process.cache.write_per_sec",
      "proxy.process.cache.KB_read_per_sec",
      "proxy.process.cache.KB_write_per_sec",
      "proxy.process.hostdb.total_entries",
      "proxy.process.hostdb.total_lookups",
      "proxy.process.hostdb.ttl",
      "proxy.process.hostdb.ttl_expires",
      "proxy.process.hostdb.re_dns_on_reload",
      "proxy.process.hostdb.bytes",
      "proxy.process.dns.total_dns_lookups",
      "proxy.process.dns.lookup_avg_time",
      "proxy.process.dns.lookup_successes",
      "proxy.process.dns.fail_avg_time",
      "proxy.process.dns.lookup_failures",
      "proxy.process.dns.retries",
      "proxy.process.dns.max_retries_exceeded",
      "proxy.process.log.bytes_buffered",
      "proxy.process.log.bytes_written_to_disk",
      "proxy.process.log.bytes_sent_to_network",
      "proxy.process.log.bytes_received_from_network",
      "proxy.process.log.event_log_error",
      "proxy.process.log.event_log_access",
      "proxy.process.log.event_log_access_fail",
      "proxy.process.log.event_log_access_skip",
      "server"
    ]

    stats.reject {|k, v| exclude.include?(k) }.each do |k, v|
      output "#{config[:scheme]}.#{k[14..-1]}", v
    end

    ok
  end

end
