
MethodLength:
  Max: 200

LineLength:
  Max: 160

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

Metrics/AbcSize:
  Max: 103
