language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
notifications:
  email:
    recipients:
      - mattjones@yieldbot.com
    on_success: change
    on_failure: always

script:
  - 'bundle exec rake default'

matrix:
  allow_failures:
    - rvm: 1.9.3
