* Sensu Plugins

This gem contains some example plugins and handlers for Sensu. Most of
them are implemented in Ruby and use the =sensu-plugin= framework (a
small gem); some also depend on additional gems (e.g. =mysql=). Some
are shell scripts! All languages are welcome.

In the future, some sort of browsing/metadata/installation system may be
implemented. For now, just clone this repository, take a look around,
and copy the plugins you want to use.

* Contributing

If you have a new plugin or handler, send a pull request! Please format
the names of scripts using dashes to separate words and with an
extension (=.rb=, =.sh=, etc), and make sure they are =chmod +x='d.
Extensions are unfortunately necessary for Sensu to be able to directly
exec plugins and handlers on Windows.

Dependencies (ruby gems, packages, etc) and other requirements should
be declared in the header of the plugin/handler file.

* License

Copyright 2011 Sonian, Inc. and contributors.

Released under the same terms as Sensu (the MIT license); see LICENSE
for details.

NOTE: When adding a plugin, copy the preceding two paragraphs to a
comment in each source file, changing the copyright holder to your own
name or organization. If you wish to use a different open source
license, please submit a pull request adding that license to the repo
and use that license's boilerplate instead.
