# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard :rspec do
  watch(%r{^spec/.+_spec\.rb$})
  watch('spec/spec_helper.rb')  { "spec" }
  watch('check_opentsdb_series.rb') { 'spec' }
  watch(%r{^spec/(fixtures|resources)(/|.rb)}) { 'spec' }
end

