#!/usr/bin/env ruby
#
# Chef Client Plugin
# ===
#
# This plugin checks to see if the OpsCode Chef client daemon is running
#
# Copyright 2011 Sonian, Inc.
#
# Released under the same terms as Sensu (the MIT license); see LICENSE
# for details.

require 'rubygems' if RUBY_VERSION < '1.9.0'
require 'sensu-plugin/util/procs'

class ChefClient < Sensu::Plugin::Check::CLI

  check_name 'chef_client'

  def run
    if Sensu::Plugin::Util::Procs.find_proc('chef-client')
      ok "Chef client daemon is running"
    else
      warning "Chef client daemon is NOT running"
    end
  end

end
