#!/usr/bin/env ruby
#
# Puppet Master Plugin
# ===
#
# This plugin checks to see if the Puppet Labs Puppet master is running
#
# Copyright 2011 James Turnbull
#
# Released under the same terms as Sensu (the MIT license); see LICENSE
# for details.

require 'rubygems'
require 'sensu-plugin/util/procs'

class PuppetMaster < Sensu::Plugin::Check::CLI

  check_name 'PUPPET MASTER'

  def run
    if Sensu::Plugin::Util::Procs.find_proc_regex(/puppetmasterd|puppet master/)
      ok 'Puppet master is running'
    else
      warning 'Puppet master is NOT running'
    end
  end
end
