#!/usr/bin/env ruby
#
# Puppet Agent Plugin
# ===
#
# This plugin checks to see if the Puppet Labs Puppet agent is running
#
# Copyright 2011 James Turnbull
#
# Released under the same terms as Sensu (the MIT license); see LICENSE
# for details.

require 'sensu-plugin/util/procs'

class PuppetAgent < Sensu::Plugin::Check::CLI

  check_name 'PUPPET AGENT'

  def run
    if Sensu::Plugin::Util::Procs.find_proc_regex(/puppetd|puppet agent/)
      ok 'Puppet agent is running'
    else
      warning 'Puppet agent is NOT running'
    end
  end
end
